"""Turn a headline into something you can act on without opening the link.

Three free, deterministic steps -- no model involved:

  facts()    pulls the actual numbers out of the text (rupee amounts, percent
             changes, basis points, quarters) so the brief can lead with them
  jargon()   flags terms worth defining, using a glossary written once
  india_relevant()  decides whether a global story touches India at all

The point is that a reader should get the substance from the brief itself and
click through only when they want the full story.
"""

from __future__ import annotations

import logging
import re

log = logging.getLogger(__name__)

# Publishers we are willing to quote. Anything not on this list still gets
# collected for corroboration counting but never becomes a lead item.
TRUSTED = {
    "ET Markets", "ET Economy", "Mint Markets", "Mint Companies",
    "BS Markets", "Hindu BusinessLine", "Reuters Business",
    "RBI and SEBI", "Moneycontrol",
}

GLOSSARY = {
    "qip": "Qualified Institutional Placement - a listed company selling new shares straight to big institutions, faster than a public issue and usually at a small discount.",
    "re-rating": "The market deciding a company deserves a higher (or lower) valuation multiple for the same earnings - the price moves without the profits changing.",
    "pat": "Profit After Tax - the bottom line, what is left after every cost and tax.",
    "ebitda": "Earnings before interest, tax, depreciation and amortisation - a rough proxy for cash generated by the core business.",
    "bps": "Basis points. 100 bps = 1 percentage point. Used for rates and margins.",
    "repo rate": "The rate at which the RBI lends to banks. It sets the floor for what everything else costs to borrow.",
    "crr": "Cash Reserve Ratio - the share of deposits banks must park with the RBI, so it controls how much they can lend.",
    "fii": "Foreign Institutional Investors - overseas funds buying Indian shares. Their flows move mid and small caps hardest.",
    "dii": "Domestic Institutional Investors - Indian mutual funds, insurers and pension money.",
    "buyback": "A company purchasing its own shares, reducing the count outstanding and lifting earnings per share.",
    "promoter": "The founding or controlling shareholder group. A change in their stake is usually a signal worth reading.",
    "pledge": "Promoters borrowing against their own shares. Heavy pledging is a known fragility.",
    "guidance": "Management's own forecast for coming quarters. A cut usually matters more than the quarter just reported.",
    "order book": "Contracted work not yet delivered - forward revenue visibility for industrials and infra names.",
    "asset quality": "How much of a lender's loan book is going bad.",
    "npa": "Non-Performing Asset - a loan that has stopped being repaid.",
    "gst": "Goods and Services Tax - India's main indirect tax.",
    "iip": "Index of Industrial Production - a monthly read on factory output.",
    "cpi": "Consumer Price Index - the headline inflation number the RBI targets.",
    "open interest": "Number of derivative contracts outstanding - a read on how much positioning sits behind a move.",
}

# Countries and themes that reliably transmit into Indian markets.
INDIA_LINKS = [
    "india", "indian", "rbi", "sebi", "nifty", "sensex", "rupee", "nse", "bse",
    "crude", "oil price", "brent", "opec",          # import bill, inflation
    "fed", "fomc", "us rates", "treasury", "dollar",  # flows into EMs
    "china", "tariff", "trade deal", "sanction", "export",
    "monsoon", "gold", "semiconductor", "h-1b", "remittance",
]

# Patterns for the numbers that actually carry information.
_NUM_PATTERNS = [
    # \d[\d,]* rather than [\d,]+ : the latter is satisfied by a bare comma,
    # which is how a chip reading only "Rs," reached the brief.
    (re.compile(r"(?:Rs\.?|₹|INR)\s?(\d[\d,]*(?:\.\d+)?)\s?"
                r"(crore|cr|lakh|billion|bn|trillion)?", re.I), "amount"),
    (re.compile(r"([+-]?\d+(?:\.\d+)?)\s?(?:per cent|percent|%)", re.I), "percent"),
    (re.compile(r"(\d+)\s?(?:basis points|bps)", re.I), "bps"),
    (re.compile(r"\b(Q[1-4]\s?FY\s?\d{2,4})\b", re.I), "quarter"),
    (re.compile(r"\b(FY\s?\d{2,4})\b", re.I), "year"),
]


def facts(text: str, limit: int = 4) -> list[str]:
    """Extract the concrete numbers from a headline or summary."""
    found: list[str] = []
    for pattern, kind in _NUM_PATTERNS:
        for m in pattern.finditer(text or ""):
            snippet = m.group(0).strip()
            snippet = re.sub(r"\s+", " ", snippet)
            if snippet.lower() not in {f.lower() for f in found}:
                found.append(snippet)
            if len(found) >= limit:
                return found
    return found


def jargon(text: str, limit: int = 3) -> list[tuple[str, str]]:
    """Terms in this story that are worth a one-line definition."""
    low = f" {(text or '').lower()} "
    hits = []
    for term, meaning in GLOSSARY.items():
        # word-boundary match so 'pat' does not fire inside 'pattern'
        if re.search(rf"\b{re.escape(term)}\b", low):
            hits.append((term.upper() if len(term) <= 4 else term.title(), meaning))
        if len(hits) >= limit:
            break
    return hits


def india_relevant(text: str) -> bool:
    """Does this global story plausibly reach Indian markets?

    Deliberately generous -- it is a filter against pure noise, not a
    judgement about importance.
    """
    low = (text or "").lower()
    return any(k in low for k in INDIA_LINKS)


def is_trusted(source: str) -> bool:
    return source in TRUSTED
