"""HTML for the two briefs.

Email clients strip most CSS, so styles are inlined and layout stays simple.
No external images or fonts -- they get blocked and leave holes.
"""

from __future__ import annotations

import html
from datetime import date, datetime

FONT = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif"
INK = "#1a1a1a"
MUTED = "#6b7280"
RULE = "#e5e7eb"
UP = "#0f7b3f"
DOWN = "#b42318"


def _esc(s) -> str:
    return html.escape(str(s), quote=False)


def _shell(title: str, subtitle: str, body: str) -> str:
    return f"""<div style="font-family:{FONT};max-width:680px;margin:0 auto;padding:24px 20px;
color:{INK};background:#ffffff;line-height:1.55;">
  <div style="border-bottom:2px solid {INK};padding-bottom:10px;margin-bottom:22px;">
    <div style="font-size:21px;font-weight:700;letter-spacing:-0.02em;">{_esc(title)}</div>
    <div style="font-size:13px;color:{MUTED};margin-top:3px;">{_esc(subtitle)}</div>
  </div>
  {body}
  <div style="margin-top:32px;padding-top:12px;border-top:1px solid {RULE};
  font-size:11px;color:{MUTED};">
    Generated by Zen from your own NSE archive and public feeds.
    Research only -- not advice, and no orders are placed.
  </div>
</div>"""


def _pct(v) -> str:
    if v is None:
        return "-"
    colour = UP if v > 0 else DOWN if v < 0 else MUTED
    return f'<span style="color:{colour};font-weight:600;">{v:+.2f}%</span>'


# --------------------------------------------------------------------------
# Brief A: daily market and news
# --------------------------------------------------------------------------

def _stat_row(b: dict) -> str:
    if not b:
        return ""
    cells = [
        ("Advancers", f'<span style="color:{UP};font-weight:600;">{b["advancers"]:,}</span>'),
        ("Decliners", f'<span style="color:{DOWN};font-weight:600;">{b["decliners"]:,}</span>'),
        ("A/D ratio", f'<b>{b["ad_ratio"]}</b>' if b.get("ad_ratio") else "-"),
        ("Median stock", _pct(b.get("median_ret"))),
        ("Turnover", f'<b>Rs {b["turnover_cr"]:,.0f} cr</b>'),
    ]
    tds = "".join(
        f'<td style="padding:8px 12px 8px 0;vertical-align:top;">'
        f'<div style="font-size:11px;color:{MUTED};text-transform:uppercase;'
        f'letter-spacing:0.04em;">{k}</div>'
        f'<div style="font-size:15px;margin-top:2px;">{v}</div></td>'
        for k, v in cells
    )
    return f'<table style="width:100%;border-collapse:collapse;margin-bottom:8px;"><tr>{tds}</tr></table>'


def _movers_table(m: dict) -> str:
    if not m or not m.get("gainers"):
        return ""

    def rows(items):
        return "".join(
            f'<tr><td style="padding:4px 8px 4px 0;font-size:13px;">'
            f'<b>{_esc(r["symbol"])}</b></td>'
            f'<td style="padding:4px 8px;font-size:13px;text-align:right;">{r["close"]:,.1f}</td>'
            f'<td style="padding:4px 8px;font-size:13px;text-align:right;">{_pct(r["ret"])}</td>'
            f'<td style="padding:4px 0;font-size:12px;text-align:right;color:{MUTED};">'
            f'{r["turnover_cr"]:,.0f}cr</td></tr>'
            for r in items
        )

    return f"""
<table style="width:100%;border-collapse:collapse;margin-top:6px;">
  <tr>
    <td style="width:50%;vertical-align:top;padding-right:14px;">
      <div style="font-size:11px;color:{MUTED};text-transform:uppercase;
      letter-spacing:0.04em;margin-bottom:4px;">Gainers</div>
      <table style="width:100%;border-collapse:collapse;">{rows(m["gainers"])}</table>
    </td>
    <td style="width:50%;vertical-align:top;">
      <div style="font-size:11px;color:{MUTED};text-transform:uppercase;
      letter-spacing:0.04em;margin-bottom:4px;">Losers</div>
      <table style="width:100%;border-collapse:collapse;">{rows(m["losers"])}</table>
    </td>
  </tr>
</table>
<div style="font-size:11px;color:{MUTED};margin-top:6px;">
  Liquidity filtered: turnover above Rs 5 cr.
</div>"""


def _tiers_table(t) -> str:
    if t is None or len(t) == 0:
        return ""
    rows = "".join(
        f'<tr><td style="padding:3px 0;font-size:13px;">{_esc(r.tier)}</td>'
        f'<td style="padding:3px 0;font-size:12px;color:{MUTED};text-align:right;">'
        f'{r.stocks:,} stocks</td>'
        f'<td style="padding:3px 0 3px 14px;font-size:13px;text-align:right;">'
        f'{_pct(r.median_ret)}</td></tr>'
        for r in t.itertuples()
    )
    return f'<table style="width:100%;border-collapse:collapse;margin-top:4px;">{rows}</table>'


def _section(name: str, articles) -> str:
    items = []
    for a in articles:
        src = _esc(a.source)
        if a.also:
            src += f" +{len(a.also)} more"
        items.append(
            f'<div style="margin-bottom:14px;">'
            f'<a href="{_esc(a.link)}" style="color:{INK};text-decoration:none;'
            f'font-size:14px;font-weight:600;line-height:1.4;">{_esc(a.title)}</a>'
            f'<div style="font-size:11px;color:{MUTED};margin-top:3px;">{src}</div>'
            f'</div>'
        )
    return f"""
<div style="margin-bottom:24px;">
  <div style="font-size:12px;font-weight:700;text-transform:uppercase;
  letter-spacing:0.06em;color:{MUTED};border-bottom:1px solid {RULE};
  padding-bottom:5px;margin-bottom:12px;">{_esc(name)}</div>
  {"".join(items)}
</div>"""


def daily_brief(sections: dict, market: dict, when: datetime) -> tuple[str, str, str]:
    """Returns (subject, html, plain text)."""
    session = market.get("session")
    b = market.get("breadth", {})
    body = ""

    if b:
        body += f"""
<div style="margin-bottom:24px;">
  <div style="font-size:12px;font-weight:700;text-transform:uppercase;
  letter-spacing:0.06em;color:{MUTED};border-bottom:1px solid {RULE};
  padding-bottom:5px;margin-bottom:10px;">Market breadth &mdash; {session}</div>
  {_stat_row(b)}
  {_tiers_table(market.get("tiers"))}
  {_movers_table(market.get("movers"))}
</div>"""

    for name, articles in sections.items():
        body += _section(name, articles)

    if not sections:
        body += (f'<div style="font-size:13px;color:{MUTED};">'
                 f'No fresh stories cleared the filters today.</div>')

    n = sum(len(v) for v in sections.values())
    tone = ""
    if b.get("ad_ratio"):
        tone = f' | A/D {b["ad_ratio"]}'
    subject = f"Zen brief {when:%d %b} | {n} stories{tone}"
    subtitle = f"{when:%A %d %B %Y} | {n} stories from {len(sections)} sections"

    text = "\n".join(
        f"[{name}] {a.title} ({a.source})"
        for name, arts in sections.items() for a in arts
    )
    return subject, _shell("Zen Market Brief", subtitle, body), text


# --------------------------------------------------------------------------
# Brief B: strategy signals -- only sent when something fires
# --------------------------------------------------------------------------

def _signal_block(s: dict) -> str:
    action = s["action"].upper()
    colour = UP if action == "BUY" else DOWN if action == "SELL" else MUTED

    def kv(label, value):
        return (f'<tr><td style="padding:3px 14px 3px 0;font-size:12px;color:{MUTED};'
                f'white-space:nowrap;vertical-align:top;">{_esc(label)}</td>'
                f'<td style="padding:3px 0;font-size:13px;">{value}</td></tr>')

    facts = "".join(
        kv(k, _esc(v)) for k, v in s.get("facts", {}).items()
    )
    reasons = "".join(
        f'<li style="margin-bottom:5px;font-size:13px;">{_esc(r)}</li>'
        for r in s.get("rationale", [])
    )
    against = "".join(
        f'<li style="margin-bottom:5px;font-size:13px;color:{MUTED};">{_esc(r)}</li>'
        for r in s.get("against", [])
    )

    against_html = ""
    if against:
        against_html = f"""
  <div style="font-size:11px;color:{MUTED};text-transform:uppercase;
  letter-spacing:0.05em;margin:14px 0 6px;">Case against</div>
  <ul style="margin:0;padding-left:18px;">{against}</ul>"""

    return f"""
<div style="border:1px solid {RULE};border-left:3px solid {colour};
padding:16px 18px;margin-bottom:18px;">
  <div style="display:block;margin-bottom:10px;">
    <span style="font-size:11px;font-weight:700;color:{colour};
    letter-spacing:0.08em;">{action}</span>
    <span style="font-size:17px;font-weight:700;margin-left:8px;">{_esc(s["symbol"])}</span>
    <span style="font-size:12px;color:{MUTED};margin-left:8px;">{_esc(s.get("name", ""))}</span>
  </div>

  <table style="border-collapse:collapse;margin-bottom:12px;">{facts}</table>

  <div style="font-size:11px;color:{MUTED};text-transform:uppercase;
  letter-spacing:0.05em;margin-bottom:6px;">Why</div>
  <ul style="margin:0;padding-left:18px;">{reasons}</ul>
  {against_html}
</div>"""


def signal_alert(signals: list[dict], context: dict, when: datetime) -> tuple[str, str, str]:
    """Detailed buy/sell note. Only called when signals is non-empty."""
    body = ""

    if context.get("note"):
        body += (f'<div style="background:#f9fafb;border:1px solid {RULE};padding:12px 14px;'
                 f'margin-bottom:20px;font-size:13px;">{_esc(context["note"])}</div>')

    buys = [s for s in signals if s["action"].lower() == "buy"]
    sells = [s for s in signals if s["action"].lower() == "sell"]

    for label, group in (("To buy", buys), ("To sell", sells)):
        if not group:
            continue
        body += (f'<div style="font-size:12px;font-weight:700;text-transform:uppercase;'
                 f'letter-spacing:0.06em;color:{MUTED};border-bottom:1px solid {RULE};'
                 f'padding-bottom:5px;margin:0 0 14px;">{label} ({len(group)})</div>')
        body += "".join(_signal_block(s) for s in group)

    if context.get("portfolio"):
        body += (f'<div style="font-size:12px;font-weight:700;text-transform:uppercase;'
                 f'letter-spacing:0.06em;color:{MUTED};border-bottom:1px solid {RULE};'
                 f'padding-bottom:5px;margin:24px 0 10px;">Portfolio effect</div>'
                 f'<div style="font-size:13px;">{_esc(context["portfolio"])}</div>')

    body += (f'<div style="margin-top:24px;padding:12px 14px;background:#fffbeb;'
             f'border:1px solid #fde68a;font-size:12px;">'
             f'<b>Before acting:</b> these are screen outputs, not instructions. '
             f'Check position sizing against your sleeve limits, and confirm nothing '
             f'material has been announced since the last close.</div>')

    subject = f"Zen SIGNAL {when:%d %b} | {len(buys)} buy, {len(sells)} sell"
    subtitle = f"{when:%A %d %B %Y} | triggered by {_esc(context.get('strategy', 'strategy'))}"

    text = "\n".join(f"{s['action'].upper()} {s['symbol']}" for s in signals)
    return subject, _shell("Zen Signal Alert", subtitle, body), text
